### ISSUE TITLE
Not working on 1.7.7.6

### ISSUE THREAD

**Issue by mrabsinthe** [stifler97/modifytokenlifetime#1] opened 2022-07-25 06:09 UTC
Admin completely blank after installation, clearing cache doesn't help, had to delete module manually via ftp and db entries via phpMyAdmin.

**Comment by stifler97** [comment] 2022-07-26 21:29
Hi. Thanks for reaching out and using the module. The problem is that the `classes/controllers/AdminController.php` in this version https://github.com/PrestaShop/PrestaShop/tree/1.7.7.6 is slightly different and there is actually no `self::AUTH_COOKIE_LIFETIME`
Instead they have put a hard coded number of `900` and it is weird!
I will add a patch and update the module in a minor version to support ps 1.7.7.6 and higher.

Anyway, this is how it logs out the admin in 1.7.7.6 if the cookie has been expired:
https://github.com/PrestaShop/PrestaShop/blob/3ce1c186e1316528b351da3ec55f84746344764b/classes/controller/AdminController.php#L2790-L2796

And this is how it is doing it in the 1.7.8.6:
https://github.com/PrestaShop/PrestaShop/blob/dc8dc1faef7185ad30fc8dcb0653524d9bfb7c82/classes/controller/AdminController.php#L2818-L2824

**Comment by stifler97** [comment] 2022-07-26 22:47
fixed

**Comment by stifler97** [comment] 2022-07-26 22:47
fixed by PR #2

**Closed by stifler97** 2022-07-26 22:47 UTC
Labels: bug, good first issue
